### ISSUE TITLE
Add noscript support

### ISSUE THREAD

**Issue by gbip** [Walleza1/Walleza1.github.io#1]
Your website does not work without javascript thus forcing user to enable javascript and compromising their privacy/security.

Would you mind fixing this issue ?

**Comment by gbip** [comment]
@Walleza1 At least add a `<noscript>` text so that your users will be aware that your website does not work without javascript.

**Comment by Walleza1** [comment]
As you may see here #2 , i have added myself a no-script tag for those who doesn't allow JavaScript to run on webpages.

**Comment by Walleza1** [comment]
As you may see here 1cf2e118d593ce9fe34f1f7033a675de8a33bb7e ,i have added myself a no-script tag for those who doesn't allow JavaScript to run on webpages.

**Comment by gbip** [comment]
Thank you :smile:
